### ISSUE TITLE
个人信息请保护好~

### ISSUE THREAD

**Issue by HunterYIboHu** [XIAZY/DriveIt#1]
~~绅士~~你好。我因为你在某个网站的活跃而来到了这里，以后还是把.git文件给删了吧……毕竟两会召开了不是，个人资料就放在那里实在是比较危险。

**Comment by XIAZY** [comment]
@HunterYIboHu 请明示……不觉得我在哪里暴露信息了啊？

**Comment by HunterYIboHu** [comment]
老司机发车的时候麻烦把驾照收好……要不得扣12分的。
P.S.我在安装`Naked`的时候，需要安装`PyYaml`，而后者在安装的时候需要`LibYaml`。而我在windos7平台上使用mingw32-make 的时候，报错：

```
make  all-recursive
process_begin: CreateProcess(NULL, make all-recursive, ...) failed.
make (e=2): ϵͳ▒Ҳ▒▒▒ָ▒▒▒▒▒ļ▒▒▒
mingw32-make: *** [all] Error 2
```

你知道是怎么回事吗？

**Comment by XIAZY** [comment]
> @HunterYIboHu 你是手动解决依赖？我是直接用包管理 pip 解决，没有问题。
> 讲真你快告诉我是在哪翻车了，我信息在哪没保护好我自己都不知道……

**Comment by HunterYIboHu** [comment]
就是你在发布《极乐院女子高寮》的时候里面有一个.git文件，我通过那个找到了这里。

>  @HunterYIboHu 你是手动解决依赖？我是直接用包管理 pip 解决，没有问题。  

我用pip安装的时候会出现下面这个错误：  

```
running build_ext
creating build\temp.win32-3.5
creating build\temp.win32-3.5\Release
checking if libyaml is compilable
error: [WinError 2] 系统找不到指定的文件。
```

**Comment by XIAZY** [comment]
我靠……这文件默认隐藏我没发现……
现在车钥匙你已经有了，上路吧……

**Comment by XIAZY** [comment]
你先上网爬点资料，我给你打个 Win 下的包试试

**Comment by HunterYIboHu** [comment]
嗯……没有隐藏。只要有git就可以顺藤摸瓜。你先把云盘上的资源修改一下吧，站里的老司机好像多会用git。

**Comment by XIAZY** [comment]
���������������������������������� GitHub ������������������������������.git ������ OS X �� Linux ����������������������
������������������������������

**Comment by HunterYIboHu** [comment]
我看到的是一堆乱码加上Github、OS X和Linux等内容

**Comment by HunterYIboHu** [comment]
我最后用安装了3.4版本，解决了这个问题。原因是我用的是Python3.5，而PyYaml正好支持到Python3.4。

**Comment by XIAZY** [comment]
原文：那也是超老的司机了吧……顺藤摸瓜到 GitHub 倒还好，反正开源就是让人用的。.git 文件在 OS X 和 Linux 默认隐藏，没注意到……
能摸到这里，难道你是程序员咯？
（OS X 自带的邮件程序估计有编码问题，又得折腾了）

**Comment by HunterYIboHu** [comment]
我不是程序员到这里写书吗……原本打算给你的脚本添加几个小功能~比如可以切换目录，选择下载哪个章节等等。

**Comment by XIAZY** [comment]
我勒个去，刚我也发现了这个问题，改代码用了受支持的库……

**Comment by HunterYIboHu** [comment]
……现在问题可以有一个新的思考方向了（你的版本不对~）

**Comment by XIAZY** [comment]
我就不是程序员……
还好没来得及 commit。反正 PyQt for Win 的二进制安装包只支持 Python 3.4，就这样不改了

**Comment by HunterYIboHu** [comment]
在README里面标注以下，还有，顺带做一个requirements.txt，之后就可以直接`pip install < requirements.txt`了。

**Comment by XIAZY** [comment]
要不你直接给我个 PR 吧，我这的 Win 是虚拟机，特慢

**Comment by XIAZY** [comment]
Fixed. 请参看最新的 commit
