### ISSUE TITLE
AttributeError: 'DM5' object has no attribute 'name'

### ISSUE THREAD

**Issue by trim21** [XIAZY/DriveIt#13]
问题链接
[cudianxin](http://www.dm5.com/manhua-cudianxinzhanzheng)
![image](https://cloud.githubusercontent.com/assets/13553903/17664873/999b619a-6329-11e6-9940-4bad4102b7d7.png)

**Comment by trim21** [comment]
测试发现所有的dm5网站的都出现这个问题,可能是dm5改版了

**Comment by XIAZY** [comment]
$BS(9%!$2fEy2qM-6u4G4G(B

?$B<+2fE*(B iPhone

$B:_(B 2016$BG/(B8$B7n(B15$BF|!$2<8a(B8:54$B!$(BTrim21 <notifications@github.com<mailto:notifications@github.com>> $B<LF;!'(B

????$B=jM-E_(Bdm5$Bf&ckE_ET=P(B??$BP$(B??,$B2DG=@'(Bdm5$B2~HGN;(B

##

**Comment by trim21** [comment]
你在说什么..........................?
邮件还是不支持utf8吗- -

**Comment by XIAZY** [comment]
$Bgy2LE*(B?$B!D!DCfJ8<+(B? GB$B!D!D(B

$B862s(B?$B!'Ey2qM-6u4G4G!$(B??$B@'2~HGN;(B

??

?$B<+2fE*(B iPhone

$B:_(B 2016$BG/(B8$B7n(B15$BF|!$2<8a(B9:08$B!$(BTrim21 <notifications@github.com<mailto:notifications@github.com>> $B<LF;!'(B

?$B:_(B?$B=:(B?..........................?
?$B7o(B?$B@'IT;Y;}(Butf8?- -

##

**Comment by XIAZY** [comment]
要死，苹果自带的邮件客户端像神经病一样

原回复：应该是改版了，等会看看

**Comment by trim21** [comment]
等明天吧,我今天想提个pr,加了一个多线程下载

**Comment by XIAZY** [comment]
多线程我其实是不敢加的，怕太快被服务器 ban IP
不过试试也是好的

**Comment by trim21** [comment]
多线程写好了=.=不知道提不提PR
额外
用了发现一个链接有问题[issue link2](http://www.dmzj.com/info/mwyyzysjsd.html)
调用down函数的时候报了错误

```
Exception in thread Thread-47:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/trim21/myProj/myDr/base.py", line 67, in run
    self.downfunc(self.comic_name, self.parent_link, self.link, self.parent_title, self.page)
  File "/home/trim21/myProj/myDr/sites.py", line 139, in down
    img_data = self.get_data(link, parent_link)
  File "/home/trim21/myProj/myDr/base.py", line 28, in get_data
    web_page = request.urlopen(req)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1141, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/lib/python3.5/http/client.py", line 983, in putrequest
    self._output(request.encode('ascii'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 7-16: ordinal not in range(128)
```

似乎是缺乏encoding

**Comment by XIAZY** [comment]
错误是发生在你的 fork 吗？

**Comment by trim21** [comment]
是的，我用你的分支下载，全部都报了错误。

**Comment by XIAZY** [comment]
你修复错误了吗？没有的话我就自己修了

**Comment by trim21** [comment]
还没修,不会修:joy:

**Comment by XIAZY** [comment]
最近实在是有点懒，等我打完几盘屁股晚点修吧😩

**Comment by trim21** [comment]
为了避免被ban准备加一个参数来控制最大线程数,不知道用什么字母比较好.........

**Comment by XIAZY** [comment]
-t threading

?$B<+2fE*(B iPhone

$B:_(B 2016$BG/(B8$B7n(B17$BF|!$2<8a(B5:37$B!$(BTrim21 <notifications@github.com<mailto:notifications@github.com>> $B<LF;!'(B

?$BN;HrLHHo(Bban$B=Z(B?$B2C0lP$;2?tMh95@):GBg(B?$BDx?t(B,$BITCNF;MQ=:(B?$B;zJlHf(B?$B9%(B.........

##

**Comment by trim21** [comment]
the Email application of OSX is so annoying

**Comment by XIAZY** [comment]
-t threading
✉️

**Comment by XIAZY** [comment]
其实 OS X 的邮件程序还好，加个 emoji 强制 UTF-8
iOS 的怎么发都是 GB
✉️

**Comment by XIAZY** [comment]
This is a test from iPhone.

??
??

?$B<+2fE*(B iPhone

$B:_(B 2016$BG/(B8$B7n(B17$BF|!$2<8a(B10:55$B!$(BTrim21 <notifications@github.com<mailto:notifications@github.com>> $B<LF;!'(B

the Email application of OSX is so annoying

##

**Comment by XIAZY** [comment]
Solved
