### ISSUE TITLE
dm5应该是又改版了........

### ISSUE THREAD

**Issue by trim21** [XIAZY/DriveIt#17]
![image](https://cloud.githubusercontent.com/assets/13553903/18098859/a0ecf97e-6f16-11e6-8907-cc619db1761a.png)

原因:原来应该是dm5没有移动端网页适配,现在有了,各种元素都重命名了

修复方法:
dm5不伪造UA,使用笔记本UA即可

```
class DM5(SharedBase):
    def get_data(self, url, referrer=''):
        self.webheader = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36',
            'Referer': referrer}
        req = request.Request(url=url, headers=self.webheader)
        web_page = request.urlopen(req)
        page_data = web_page.read()
        return page_data

    def __init__(self, url):
```

重写了get_data方法,但是在文件头要`from urllib import request`,有没有什么优雅一点的办法...

**Comment by XIAZY** [comment]
这个好办

**Comment by XIAZY** [comment]
![2016-08-31 11 29 33](https://cloud.githubusercontent.com/assets/8736607/18115003/6009632c-6f6e-11e6-959a-2fc3d42d5b2f.png)
搞定了，增加了 `is_desktop` 判断
