### ISSUE TITLE
可以在header里添加压缩支持

### ISSUE THREAD

**Issue by trim21** [XIAZY/DriveIt#20]
requests是支持自动解码gzip, deflate和sdch,下一次commit的时候顺手在header里加上
`"Accept-Encoding": "gzip, deflate, sdch"`,应该对速度有帮助

**Comment by XIAZY** [comment]
OK. Thanks

**Comment by iamtowne** [comment]
拉区DMZJ的时候遇到这个问题:
line 127, in get_page_info
    inner_page_data = self.get_data(parent_link).decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

**Comment by XIAZY** [comment]
我猜是网络问题？很奇怪，这种错误没道理发生

On 2016年12月2日 -0500 AM3:49, towne <notifications@github.com>, wrote:

拉区DMZJ的时候遇到这个问题:
line 127, in get_page_info
inner_page_data = self.get_data(parent_link).decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

**Comment by iamtowne** [comment]
我的命令:python3 ./driveit.py http://www.dmzj.com/info/chuanlingwuyu.html
返回打印:
url http://www.dmzj.com/info/chuanlingwuyu.html header  {'Referer': '', 'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 8_0 like Mac OS X) AppleWebKit/600.1.3 (KHTML, like Gecko) Version/8.0 Mobile/12A4345d Safari/600.1.4'}
Traceback (most recent call last):
  File "./driveit.py", line 99, in <module>
    website_object = SiteClass(user_input_url)
  File "/Users/~/Documents/~/DriveIt-master/sites.py", line 107, in __init__
    self.flyleaf_data = self.get_data(self.flyleaf_url).decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

dm5的体验很完美[赞].

**Comment by XIAZY** [comment]
动漫之家看起来改版了啊，是最近出现的吗？别的漫画有无类似问题？


2016年12月2日 -0500 AM4:02 towne <notifications@github.com>，写道：

我的命令:python3 ./driveit.py http://www.dmzj.com/info/chuanlingwuyu.html
返回打印:
url http://www.dmzj.com/info/chuanlingwuyu.html header {'Referer': '', 'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 8_0 like Mac OS X) AppleWebKit/600.1.3 (KHTML, like Gecko) Version/8.0 Mobile/12A4345d Safari/600.1.4'}
Traceback (most recent call last):
File "./driveit.py", line 99, in
website_object = SiteClass(user_input_url)
File "/Users//Documents//DriveIt-master/sites.py", line 107, in init
self.flyleaf_data = self.get_data(self.flyleaf_url).decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

dm5的体验很完美[赞].

**Comment by XIAZY** [comment]
还有就是请新开一个 issue，这样可能会打扰到楼主，谢谢


2016年12月2日 -0500 AM4:02 towne <notifications@github.com>，写道：

我的命令:python3 ./driveit.py http://www.dmzj.com/info/chuanlingwuyu.html
返回打印:
url http://www.dmzj.com/info/chuanlingwuyu.html header {'Referer': '', 'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 8_0 like Mac OS X) AppleWebKit/600.1.3 (KHTML, like Gecko) Version/8.0 Mobile/12A4345d Safari/600.1.4'}
Traceback (most recent call last):
File "./driveit.py", line 99, in
website_object = SiteClass(user_input_url)
File "/Users//Documents//DriveIt-master/sites.py", line 107, in init
self.flyleaf_data = self.get_data(self.flyleaf_url).decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

dm5的体验很完美[赞].

**Comment by XIAZY** [comment]
已添加，谢谢指出
