### ISSUE TITLE
DMZJ 显示:UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

### ISSUE THREAD

**Issue by townetowne** [XIAZY/DriveIt#21]
我的命令:python3 ./driveit.py http://www.dmzj.com/info/chuanlingwuyu.html
返回打印:
url http://www.dmzj.com/info/chuanlingwuyu.html header {'Referer': '', 'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 8_0 like Mac OS X) AppleWebKit/600.1.3 (KHTML, like Gecko) Version/8.0 Mobile/12A4345d Safari/600.1.4'}
Traceback (most recent call last):
File "./driveit.py", line 99, in 
website_object = SiteClass(user_input_url)
File "/Users//Documents//DriveIt-master/sites.py", line 107, in init
self.flyleaf_data = self.get_data(self.flyleaf_url).decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

**Comment by XIAZY** [comment]
是最近出现的吗？别的漫画页有无类似问题？


2016年12月2日 -0500 AM4:12 towne <notifications@github.com>，写道：

我的命令:python3 ./driveit.py http://www.dmzj.com/info/chuanlingwuyu.html
返回打印:
url http://www.dmzj.com/info/chuanlingwuyu.html header {'Referer': '', 'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 8_0 like Mac OS X) AppleWebKit/600.1.3 (KHTML, like Gecko) Version/8.0 Mobile/12A4345d Safari/600.1.4'}
Traceback (most recent call last):
File "./driveit.py", line 99, in
website_object = SiteClass(user_input_url)
File "/Users//Documents//DriveIt-master/sites.py", line 107, in init
self.flyleaf_data = self.get_data(self.flyleaf_url).decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

**Comment by townetowne** [comment]
别的测试过基本是对的. 有的长篇的也打不出来，比如海贼王 提示长度溢出

**Comment by XIAZY** [comment]
感谢反馈。最近超级忙，有空的时候会看一下能否修复。


2016年12月2日 -0500 AM4:22 towne <notifications@github.com>，写道：

别的测试过基本是对的. 有的长篇的也打不出来，比如海贼王 提示长度溢出

**Comment by XIAZY** [comment]
已解决。原因是 `gzip` 解码。
![2016-12-29 6 38 40](https://cloud.githubusercontent.com/assets/8736607/21543413/04e8596a-cd94-11e6-87ba-075441da24a9.png)

**Comment by XIAZY** [comment]
请问修复后还有类似问题吗？

**Comment by townetowne** [comment]
已经修复，感谢🙏，另外请教 上面截图用的是什么ide, 我是 macOS 有好用的没

**Comment by XIAZY** [comment]
PyCharm


2017年1月19日 -0500 AM1:34 towne <notifications@github.com>，写道：

已经修复，感谢🙏，另外请教 上面截图用的是什么ide, 我是 macOS 有好用的没
