### ISSUE TITLE
dm5 manhua.dmzj 都挂了

### ISSUE THREAD

**Issue by trim21** [XIAZY/DriveIt#22]
本来是想加个代理支持....都加完了测试的时候发现挂了= =

[http://manhua.dmzj.com/fengxia/](http://manhua.dmzj.com/fengxia/)
[http://www.dm5.com/manhua-reclksdysjsh/](http://www.dm5.com/manhua-reclksdysjsh/)

准备写个单元测试,想动手修复发现连定位问题发生的具体函数都很难....

ps:readme里面的这个链接已经失效了
```
http://www.dmzj.com/info/shenshimenlianaizhanzheng.html is a flyleaf page of DMZJ
```

**Comment by XIAZY** [comment]
好吧我看看……前几天测试还是好的，这网站不讲道理


2017年1月19日 -0500 PM5:51 Trim21 <notifications@github.com>，写道：

本来是想加个代理支持....都加完了测试的时候发现挂了= =

http://manhua.dmzj.com/fengxia/
http://www.dm5.com/manhua-reclksdysjsh/

准备写个单元测试,想动手修复发现连定位问题发生的具体函数都很难....

ps:readme里面的这个链接已经失效了


http://www.dmzj.com/info/shenshimenlianaizhanzheng.html is a flyleaf page of DMZJ

**Comment by XIAZY** [comment]
<img width="937" alt="2017-01-19 6 52 28" src="https://cloud.githubusercontent.com/assets/8736607/22130186/a2306d8a-de78-11e6-85e7-923289d3d694.png">

![2017-01-19 6 52 13](https://cloud.githubusercontent.com/assets/8736607/22130187/a230d1a8-de78-11e6-9fbd-caafc2bd74c4.png)

dm5 我测试没有问题，dmzj 确实挂了

**Comment by XIAZY** [comment]
已修复，请试试看现在是否还有这个bug

**Comment by trim21** [comment]
![qq 20170120235528](https://cloud.githubusercontent.com/assets/13553903/22155906/123cccb0-df6c-11e6-865f-0b3543afff8a.png)
![qq 20170120235625](https://cloud.githubusercontent.com/assets/13553903/22155905/12373d72-df6c-11e6-92af-04e17ce8e669.png)
怪了= =....

**Comment by XIAZY** [comment]
把 try except 那段代码拿出来，我看看报错吧


2017年1月20日 -0500 AM10:56 Trim21 <notifications@github.com>，写道：

[qq 20170120235528]<https://cloud.githubusercontent.com/assets/13553903/22155906/123cccb0-df6c-11e6-865f-0b3543afff8a.png>
[qq 20170120235625]<https://cloud.githubusercontent.com/assets/13553903/22155905/12373d72-df6c-11e6-92af-04e17ce8e669.png>
怪了= =....

**Comment by trim21** [comment]
保存文件的部分有点问题,等一下我提个pr吧.......

**Comment by XIAZY** [comment]
那会不会是 windows specific 的bug……


2017年1月20日 -0500 PM2:19 Trim21 <notifications@github.com>，写道：

保存文件的部分有点问题,等一下我提个pr吧.......

**Comment by trim21** [comment]
错误捕捉有逻辑问题..
windows的目录中不能有`:`,但是实际运行`os.makedirs(path)`的时候又没能捕捉到`NotADirectoryError`...导致没能运行`os.makedirs(path_safe)` 我觉得改成强制过滤比较好...
mac的目录中可以有`:`?

**Comment by XIAZY** [comment]
那就好办了，base.py 里有一个safe啥的函数是处理这种情况的，把字符加进去就好


2017年1月20日 -0500 PM2:30 Trim21 <notifications@github.com>，写道：

错误捕捉有逻辑问题..
windows的目录中不能有:,但是实际运行os.makedirs(path)的时候又没能捕捉到NotADirectoryError...导致没能运行os.makedirs(path_safe) 我觉得改成强制过滤比较好...
mac的目录中可以有:?

**Comment by trim21** [comment]
之前我写的错误捕捉有问题....修复了
感觉不应该用try except当分支语句.......

**Comment by trim21** [comment]
不是windows特有的bug 应该是mac没符合bug触发的条件.多线程下载+目录中有不合法的字符就会触发这个bug

**Comment by XIAZY** [comment]
这里为什么要这么写…… pass 太多了，if 如果要判断为否的话用 if not 就可以了，try except 多层嵌套没有意义，多个 except 就可以处理不同的错误


2017年1月20日 -0500 PM2:55 Trim21 <notifications@github.com>，写道：

不是windows特有的bug 应该是mac没符合bug触发的条件.多线程下载+目录中有不合法的字符就会触发这个bug

**Comment by XIAZY** [comment]
我其实还是有点没搞懂，错误的触发条件的多线程+特殊字符？


2017年1月20日 -0500 PM2:55 Trim21 <notifications@github.com>，写道：

不是windows特有的bug 应该是mac没符合bug触发的条件.多线程下载+目录中有不合法的字符就会触发这个bug

**Comment by trim21** [comment]
这里的确需要这么写.........
这里有可能发生两个错误,,还有可能两个错误同时发生......
多线程抢占创建文件夹会产生FileExistsError
目录不合法会NotADirectoryError
多个ecxept能处理两种错误分别发生,但是不能处理两个错误同时发生........
比如一个try多个except的代码
```
try:
    os.mkdir(path)
except NotADirectoryError as e:
    os.mkdir(path_safe)
except FileExistsError as e:
    pass
```
比如`re:`因为有`:`会产生NotADirectoryError错误,落入第一个except中,但是多线程的情况下还是会多个线程同时`mkdir`发生FileExistsError

**Comment by trim21** [comment]
好吧,判断文件夹是否存在的确是多余了...直接交给FileExistsError处理就好了

**Comment by XIAZY** [comment]
试试？

**Comment by trim21** [comment]
试什么?

**Comment by XIAZY** [comment]
修复了一下，强制所有文件夹名字使用删去特殊字符的字符串
在 2017年1月20日，下午5:22，Trim21 <notifications@github.com<mailto:notifications@github.com>> 写道：


试什么?

**Comment by trim21** [comment]
没问题了

**Comment by XIAZY** [comment]
OK，谢谢你提出问题
