### ISSUE TITLE
我居然来提issue了

### ISSUE THREAD

**Issue by trim21** [XIAZY/DriveIt#3]
似乎是idm5的网页结构变了？

···
URL?
http://www.dm5.com/manhua-cudianxinzhanzheng/
Traceback (most recent call last):
  File ".\driveit.py", line 30, in <module>
    ref_box = website_object.get_parent_info()
  File "C:\Users\Niu\DriveIt\sites.py", line 72, in get_parent_info
    ref_title = li.a['title']
  File "C:\Users\Niu\AppData\Local\Programs\Python\Python35\lib\site-packages\bs4\element.py", line 958, in **getitem**
    return self.attrs[key]
KeyError: 'title'
···
刚刚爬[粗点心战争](http://www.dm5.com/manhua-cudianxinzhanzheng/)的时候报的错
如果楼主有心修复就好啦-。-

**Comment by XIAZY** [comment]
你可以看一下，DM5 有些漫画是腾讯版权漫，爬不了的

PS 这玩意真有人用啊

Sent from Outlookhttp://taps.io/outlookmobile Mobile

On Sat, May 21, 2016 at 12:02 PM -0700, "Trim21" <notifications@github.com<mailto:notifications@github.com>> wrote:

似乎是idm5的网页结构变了？

・・・
URL?
http://www.dm5.com/manhua-cudianxinzhanzheng/
Traceback (most recent call last):
File ".\driveit.py", line 30, in
ref_box = website_object.get_parent_info()
File "C:\Users\Niu\DriveIt\sites.py", line 72, in get_parent_info
ref_title = li.a['title']
File "C:\Users\Niu\AppData\Local\Programs\Python\Python35\lib\site-packages\bs4\element.py", line 958, in getitem
return self.attrs[key]
KeyError: 'title'
・・・
刚刚爬粗点心战争http://www.dm5.com/manhua-cudianxinzhanzheng/的时候报的错
如果楼主有心修复就好啦-。-

―

**Comment by trim21** [comment]
找到问题了,不是版权问题,是这漫画有一部分是在页面上是隐藏的,点击一下才会现实所有的连接,所以html结构和之前的不一样

```
             <li><a class="tg" href="/m176910/" title="粗点心战争 第8话">第8话</a>（9页）</li>
                                    <li><a class="tg" href="/m176726/" title="粗点心战争 第7话">第7话</a>（9页）</li>
                                    <li><a href="javascript:ShowHide('cbc',2,3,'cb','in3 fll', 'in4 fll');"> 第7话-第1话</a></li>
                                </ul>
                                <ul class="nr6 lan2" id="cbc_2">
                                    <li><a class="tg" href="/m176727/" title="粗点心战争 第7话">粗点心战争漫画&nbsp;第7话</a>（10页）</li>
```

在爬到

```
 <li><a href="javascript:ShowHide('cbc',2,3,'cb','in3 fll', 'in4 fll');"> 第7话-第1话</a></li>
```

的时候因为没有title属性所以报错了

**Comment by XIAZY** [comment]
感谢，知道原因了。等会有空就去修复。

**Comment by trim21** [comment]
我修复完了2333
是不是可以发一个pull request,

**Comment by XIAZY** [comment]
6666  😊
来发个 PR 吧
在 2016年5月22日，下午5:31，Trim21 <notifications@github.com<mailto:notifications@github.com>> 写道：

我修复完了2333
是不是可以发一个pull request,

**Comment by XIAZY** [comment]
很尴尬
![](https://ooo.0o0.ooo/2016/05/22/574185db0109a.png)

**Comment by Trim21** [comment]
![qq 20160522181206](https://cloud.githubusercontent.com/assets/13553903/15453444/c06d7354-2048-11e6-9ffc-c07203c985ff.png)
是有点尴尬,我这里没问题..
win10 64 python35

**Comment by trim21** [comment]
![qq 20160522181206](https://cloud.githubusercontent.com/assets/13553903/15453449/ee77e202-2048-11e6-849f-35f13f95cd31.png)
是很尴尬..我这里运行没有问题

win10 64 python35

**Comment by trim21** [comment]
太尴尬了,改过了之后缩进还是错的.修复好了

**Comment by XIAZY** [comment]
缩进不要紧，IDE 已经自动帮我修好了
下不到漫画这个问题实在是太尴尬了
![屏幕快照 2016-05-22 下午6.16.23.png](https://ooo.0o0.ooo/2016/05/22/5741887e96d2b.png)

**Comment by trim21** [comment]
不是可以吗,我现在正爬着呢.....

**Comment by XIAZY** [comment]
好吧……我这边只有粗点心战争爬不下来，其他都没问题。
对付这种情况不用那么复杂……可以看新的 commit

**Comment by trim21** [comment]
我刚刚还在想海贼这样的有9页的怎么办,正在看bs的文档233
