### ISSUE TITLE
png 格式 漫画 被 误保存 为 jpg 格式

### ISSUE THREAD

**Issue by bllli** [XIAZY/DriveIt#9]
测试url 
 `http://www.dm5.com/manhua-yiquanchaoren/`
下载至‘外传：第8话 ’可复现，图片无法打开，修改后缀名为 .png后图片可正常观看

图片url 如
`http://manhua1025.61-174-50-141.cdndm5.com/11/10684/399544/1_7450.jpg?cid=399544&key=26598c8617417b16446db25625610c9a`
`http://manhua1023.61-174-50-131.cdndm5.com/11/10684/145458/3_5957.png?cid=145458&key=26598c8617417b16446db25625610c9a`
里有图片的格式，很好识别

p.s. 您的源码非常有帮助，谢谢您～

**Comment by XIAZY** [comment]
��������URL ���� jpg ���������������� png?

**Comment by bllli** [comment]
我看到的回复是 乱码 和 URL jpg png? 额

**Comment by XIAZY** [comment]
原回复：
为啥呢？URL 里是 jpg 格式但是实际上是 png?

苹果的锅，中文回帖自动不用 UTF-8……
✉️

**Comment by bllli** [comment]
URL里面是也是 png , 但是你用的 jpg 后缀名保存的

**Comment by XIAZY** [comment]
你给我发的 URL:
http://manhua1025.61-174-50-141.cdndm5.com/11/10684/399544/1_7450.jpg?cid=399544&key=26598c8617417b16446db25625610c9a
不就是用 jpg 的吗
??

**Comment by bllli** [comment]
抱歉我没说清楚,
我已经修改issue了，添加了一个png的URL
http://manhua1023.61-174-50-131.cdndm5.com/11/10684/145458/3_5957.png?cid=145458&key=26598c8617417b16446db25625610c9a
我想说明的是URL里有后缀名

**Comment by XIAZY** [comment]
OK 这个简单，等会晚些去改改
感谢反馈🙏

**Comment by bllli** [comment]
好的 谢谢～

**Comment by XIAZY** [comment]
要不你直接给我个 PR 吧，有点懒得开电脑了……😊

**Comment by bllli** [comment]
新手求罩 :relaxed:

**Comment by XIAZY** [comment]
刚看了，我觉得最好加个判断，然后直接从URL中提取扩展名比较好？
因为有可能会遇到非 jpg, png 的情况
用正则或者其他方法试试吧

**Comment by bllli** [comment]
好的,我再试试

**Comment by bllli** [comment]
觉得如果每个 URL 都用正则去识别的话比较浪费， 
所以改成了只有后缀名不是 png 和 jpg 的情况才使用正则。
请多赐教 :relaxed:

**Comment by XIAZY** [comment]
如果正则 compile 过的话，我个人还是觉得这种方法并不会带来很大的性能损耗
还有一个问题就是，上面的判断语句如果遇到随机文件吗中含有 jpg 但是扩展名并不是 jpg 的情况。则会错误判断。
个人见解啦
😊

**Comment by bllli** [comment]
感觉随机码里面有 `.jpg?` 的情况非常罕见，前面是点， 后面是问号。
这样的正则性能损耗不高的话， 那还是直接正则吧，安全多了。

**Comment by XIAZY** [comment]
嗯，我个人感觉，既然都用 Python 了就怎么方便怎么来吧，反正解释器已经够慢了……😢

**Comment by bllli** [comment]
哈哈， 有道理。以前用 Python 控制浏览器做爬虫慢的简直想砸电脑。
